### ISSUE TITLE
Change specification of range min() & max() to impose fewer restrictions and incur smaller costs

### ISSUE THREAD

**Issue by tonyelewis** [ericniebler/stl2#166] opened 2016-02-25 14:50 UTC
Overview
-----

Following on from ericniebler/range-v3#285, I propose changing the specification for the range versions of `min()`, `max()` to:
 * not require the range's value_type be `Copyable`
 * guarantee no copies / assignments of values (except if required to return the result value?)
 * prefer returning the result by the range's reference_type (which is cheaper and allows write access where appropriate)
 * return the result by the range's value_type when necessary - when the range argument is an rvalue and isn't a view

**Aside**: AFIAU, the current implementations in ericniebler/range-v3@7297e4a further require the range's value_type be assignable, though that isn't concept-checked in the specification. Eg it fails on `std::map<int, int>` because `std::pair<const int, int>` isn't assignable.)

Steps
-----

**Step 1**: Add a new general range trait along the lines of:

~~~~~.cpp
/// \brief The type that functions should use to return one of the elements from a range argument of the given type
///
/// Where possible (ie for lvalue or view ranges),   return the range's entries by its reference type
/// Otherwise      (ie for rvalue, non-view ranges), return the range's entries by its value type
///
/// Example:
///
///     template <typename Rng>
///     range_element_return_t<Rng> some_fn(Rng &&rng) {
///         [...]
///     }
template <typename T>
using range_element_return_t = typename std::conditional<
    std::is_lvalue_reference<T>() || View<T>(),
    range_reference_t<T>,
    range_value_t<T>
>::type;
~~~~~

**Step 2**:Change the return type of `min()` and `max()` from the range's value_type to `range_element_return_t<Rng>`. This allows returning by reference where possible, but still returning by value elsewhere.

**Step 3**: Add a guarantee that `min()` and `max` will perform no copies / assignments of values other than are required to return the result. This can be achieved with an implementation that passes through to the iterator-based `min_element()` / `max_element()` fuctions, eg:
~~~~~.cpp
return *ranges::max_element(
   rng,
   std::forward<Comp>( comp ),
   std::foward<Proj>( proj )
);
~~~~~

**Step 4**: Drop the `Copyable` requirement (because, for example, the implementation described above works on `vector<unique_ptr<int>>`). I'm not completely clear about what requirements *are* still needed. My guess is something:
~~~~~.cpp
   std::is_lvalue_reference<T>()
|| ranges::View<T>()
|| std::is_move_constructible<range_value_t<Rng>>
~~~~~

Other issues
-----
 * Should the same ideas also be applied to `minmax()` too?
 * Should the same ideas also be applied to the `initializer_list` versions of these functions?

**Comment by CaseyCarter** [comment] 2016-02-26 01:03
> Aside: AFIAU, the current implementations in ericniebler/range-v3@7297e4a further require the range's `value_type` be assignable, though that isn't concept-checked in the specification.

The `Copyable` concept requires both copy construction and copy assignment.

> * Should the same ideas also be applied to `minmax()` too?

Definitely yes, for consistency.

> * Should the same ideas also be applied to the `initializer_list` versions of these functions?

This change has the potential to silently introduce lifetime bugs in existing code. E.g.,

```c++
auto&& foo = std::min({1,2,3});
do_something_with(foo);
```

works in C++14 but would have UB with this change. I find it unlikely that any real code in the wild uses `auto&& foo = std::min(...)`, so any resulting breakage should be minimal but it needs to be noted in any case.

>  Drop the `Copyable` requirement

The value type needs to be `CopyConstructible` only if it's returned by value. Expressing that may be messy ;)

**Comment by CaseyCarter** [comment] 2016-02-26 01:28
Did a bit of research, and it looks like there's been some discussion before ([LWG915](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-closed.html#915), [LWG1308](http://www.open-std.org/jtc1/sc22/wg21/docs/lwg-closed.html#1308)) of whether the `initializer_list` overloads should return by value or by reference. LWG seems to prefer that those overloads return by value.

**Comment by tonyelewis** [comment] 2016-02-27 13:33
Thanks very much for the above responses. I'll try to break my responses up a bit...

**Comment by tonyelewis** [comment] 2016-02-27 13:37
> The Copyable concept requires both copy construction and copy assignment.

Ah - OK. So then... I was working with std::pair<const int, int>, which passes the `Copyable` concept:

~~~~~.cpp
static_assert(   ranges::Copyable< int                       >(), "int                       should    be Copyable" ); // Passes
static_assert( ! ranges::Copyable< std::unique_ptr<int>      >(), "std::unique_ptr<int>      shouldn't be Copyable" ); // Passes
static_assert( ! ranges::Copyable< std::pair<const int, int> >(), "std::pair<const int, int> shouldn't be Copyable" ); // Fails
~~~~~

...but which the compiler won't allow to be assigned (`assignment of read-only member ‘std::pair<const int, int>::first’`). Is that compiler error of the sort that concepts are unable to detect?

**Comment by tonyelewis** [comment] 2016-02-27 13:42
Re the `initializer_list` version...

Yes, (FWIW) I think I was already persuaded that these overloads should be left alone after your first comment, before you showed the LWG decisions. Thanks.

**Comment by tonyelewis** [comment] 2016-02-27 14:07
Re the range versions of `min()`, `max()` and `minmax()`...

Before the details, here are my top high-level goals:
 * **Eradicate value copies/assignments within the algorithms themselves**
 * **Return references for lvalue / view range args (cheap; non-restrictive; allows write)**
 * **Define a standard strategy for functions that return one or more elements of a range argument.** Current examples: `min()`, `max()`, `minmax()`, `front()` and `back()`; maybe many more in the future. Perhaps the strategy can be encapsulated in traits/concepts that can be dumb now but upgraded later on?

**Comment by tonyelewis** [comment] 2016-02-27 15:17
> The value type needs to be `CopyConstructible` only if it's returned by value. Expressing that may be messy ;)

Hmm. Makes sense. A few more thoughts...

So would that need to be a new concept, say `ElementReturnable`, along the lines of the following?

~~~~~.cpp
std::is_lvalue_reference<Rng>()
||
View<Rng>()
||
CopyConstructible<range_value_t<Rng>
~~~~~

BTW, would it be crazy to try to add a `std::forward` to the implementation like:
~~~~~.cpp
return std::forward<range_entry_return_t<Rng>>(
   *ranges::max_element( [...] )
);
~~~~~

...so that the last part of `ElementReturnable` only need be `MoveConstructible<range_value_t<Rng>>`?

If this is all a bit complicated, would it be simpler to always return by reference and reject rvalue, non-view range arguments at compile time (ideally with a message like the one given attempts to pipe an rvalue into a view)? This has the advantage that any future changes to handling rvalue, non-view range arguments will be non-breaking.

**Comment by ericniebler** [comment] 2016-02-27 22:39
>Eradicate value copies/assignments within the algorithms themselves

I am not convinced this is universally desirable. Consider calling `max` on a range of `int`s. Making a local copy of an `int` and performing comparisons against  it is likely to be more efficient than repeatedly indirecting through an iterator, as `max_element` does. `max_element` is there if you need it. I don't see a compelling reason to make `max` do basically what `max_element` already does.

**Comment by ericniebler** [comment] 2016-02-27 23:10
> I was working with `std::pair<const int, int>`, which passes the `Copyable` concept

It shouldn't, but `std::pair` has tons of bugs like this. The trouble is that its copy assignment operator is not constrained in any way. I'm certain there's an issue for this, but I can't find it right now.

**Comment by ericniebler** [comment] 2016-03-08 15:19
@tonyelewis, do you have any thoughts about my comment? I'm inclined to close this issue By Design.

**Comment by tonyelewis** [comment] 2016-03-08 22:26
Apologies for the delay.

Understood re `std::pair` - thanks for the info.

I performed some very rough benchmarks to investigate your hypothesis abut the current implementation being faster on `int`s. Broad summary: yes, much faster on GCC; no, no faster on Clang.

I'm not sure what what my overall opinion is now. A few thoughts:
 * I'm reasonably happy with the idea of there being *something* that's just a thin wrapper for `max_element` to make clients' syntax slightly cleaner (though maybe `max` shouldn't be it).
 * More generally, I like the idea of thin wrappers for iterator-returning functions to make them return values or throw if they can't (vaguely like `map::at`). I think these small differences to syntax can add up to a big improvement in client code readability (a la `sort( a.begin(), a.end() );` -> `sort( a );`).
 * I feel the two aspects (returning an iterator versus returning the actual result; algorithmically using references versus values (for fast handling of `int`s etc)) are (fairly) orthogonal. That makes me slightly queasy about `max` varying both of them wrt `max_element`.
 * I wonder whether the users would know that `max` uses a different algorithmic approach that they should prefer in certain cases, such as for `std::vector<int>` on GCC. In which case, is that benefit worth the costs?

Overall, I'm not sure. In a ideal world, I'd vote for this to be mulled over a bit by a few people at your level of expertise. That said, I realise everyone's time is limited, and I'm very happy for you to close this as By Design. Either way, thanks for your time and effort in considering this issue.

**Comment by tonyelewis** [comment] 2016-03-10 09:58
Update:

I've had another quick look at my benchmark after watching some of Chandler Carruth's "[...] Oh My!" talk.

It's still very rough and really shouldn't be taken to too seriously but...

Under both GCC and Clang, it now shows no clear speed difference on ints between the current `max` implementation and an implementation that wraps `max_element`.

**Closed** 2016-10-28 19:10 UTC
Labels: invalid
