### ISSUE TITLE
Can size return a signed type?

### ISSUE THREAD

**Issue by mzeren-vmw** [ericniebler/stl2#140] opened 2015-11-01 15:41 UTC
In 24.12 `size` returns the unsigned type `size_t`. Can it instead return a signed type? This would be consistent with the statement in B.2.3 where we have "...  Although sensible from a soundness point of view, the author of this paper feels this is potentially a rich source of confusion. This paper hews closer to the current standard by having only one associated type, DifferenceType, and requiring it to be signed.".

I was hoping that STL2 might address the problem in the existing STL where `assert(vec.size() == vec.end() - vec.begin())` compares an unsigned integer to a signed integer.

Do you have pointers to prior discussions on this topic?

**Comment by ericniebler** [comment] 2015-11-02 18:36
I'm very sympathetic to this POV. I would dearly love to kill unsigned integers throughout the STL. IMO, this deserves its own paper. I can't unilaterally make this decision for the entire C++ community. Would you like to write a paper? I could help.

**Comment by CaseyCarter** [comment] 2016-10-14 02:12
Duplicate of #182.

**Closed by CaseyCarter** 2016-10-14 02:12 UTC
